"""initial schema

Revision ID: 299ec9cc3f9f
Revises: 
Create Date: 2026-07-14 22:46:33.306830
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '299ec9cc3f9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysts',
    sa.Column('username', sa.String(length=48), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysts_username'), ['username'], unique=True)

    op.create_table('customers',
    sa.Column('customer_ref', sa.String(length=24), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('customer_type', sa.String(length=24), nullable=False),
    sa.Column('tier', sa.String(length=24), nullable=False),
    sa.Column('risk_classification', sa.String(length=16), nullable=False),
    sa.Column('onboarding_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('preferred_channel', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=48), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_customer_ref'), ['customer_ref'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_customer_type'), ['customer_type'], unique=False)

    op.create_table('devices',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('os', sa.String(length=48), nullable=False),
    sa.Column('browser', sa.String(length=48), nullable=False),
    sa.Column('manufacturer', sa.String(length=48), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_fingerprint'), ['fingerprint'], unique=True)

    op.create_table('endpoints',
    sa.Column('endpoint_ref', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('service_owner', sa.String(length=64), nullable=False),
    sa.Column('application', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('encryption_profile', sa.String(length=80), nullable=False),
    sa.Column('security_posture', sa.String(length=16), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('data_sensitivity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('active_from', sa.DateTime(), nullable=False),
    sa.Column('deprecated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endpoints_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_endpoints_criticality'), ['criticality'], unique=False)
        batch_op.create_index(batch_op.f('ix_endpoints_endpoint_ref'), ['endpoint_ref'], unique=True)

    op.create_table('event_ledger',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_uid', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('event_category', sa.String(length=24), nullable=False),
    sa.Column('event_source', sa.String(length=32), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('ip_id', sa.String(length=36), nullable=True),
    sa.Column('session_ref', sa.String(length=48), nullable=True),
    sa.Column('endpoint_id', sa.String(length=36), nullable=True),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ref_table', sa.String(length=24), nullable=True),
    sa.Column('ref_id', sa.String(length=48), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_ledger', schema=None) as batch_op:
        batch_op.create_index('idx_ledger_customer_time', ['customer_id', 'event_time'], unique=False)
        batch_op.create_index('idx_ledger_endpoint_time', ['endpoint_id', 'event_time'], unique=False)
        batch_op.create_index('idx_ledger_type_time', ['event_type', 'event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_ledger_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_ledger_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_ledger_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_ledger_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_ledger_event_uid'), ['event_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_ledger_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_ledger_session_ref'), ['session_ref'], unique=False)

    op.create_table('ingestion_audit',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('validation_ok', sa.Boolean(), nullable=False),
    sa.Column('normalized', sa.Boolean(), nullable=False),
    sa.Column('enriched', sa.Boolean(), nullable=False),
    sa.Column('persisted', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload_preview', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_audit_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_audit_received_at'), ['received_at'], unique=False)

    op.create_table('locations',
    sa.Column('country', sa.String(length=48), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=48), nullable=False),
    sa.Column('region', sa.String(length=48), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index('idx_location_country_city', ['country', 'city'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_country'), ['country'], unique=False)

    op.create_table('risk_memory',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('behavioural_confidence', sa.Float(), nullable=False),
    sa.Column('baseline_confidence', sa.Float(), nullable=False),
    sa.Column('amt_mean', sa.Float(), nullable=False),
    sa.Column('amt_median', sa.Float(), nullable=False),
    sa.Column('amt_std', sa.Float(), nullable=False),
    sa.Column('amt_max', sa.Float(), nullable=False),
    sa.Column('txn_frequency_daily', sa.Float(), nullable=False),
    sa.Column('auth_success_rate', sa.Float(), nullable=False),
    sa.Column('preferred_hours', sa.JSON(), nullable=False),
    sa.Column('normal_countries', sa.JSON(), nullable=False),
    sa.Column('preferred_devices', sa.JSON(), nullable=False),
    sa.Column('home_lat', sa.Float(), nullable=True),
    sa.Column('home_lon', sa.Float(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('historical_anomalies', sa.Integer(), nullable=False),
    sa.Column('false_positives', sa.Integer(), nullable=False),
    sa.Column('true_positives', sa.Integer(), nullable=False),
    sa.Column('behavioural_variance', sa.Float(), nullable=False),
    sa.Column('decay_factor', sa.Float(), nullable=False),
    sa.Column('last_recalculated', sa.DateTime(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_risk_entity')
    )
    with op.batch_alter_table('risk_memory', schema=None) as batch_op:
        batch_op.create_index('idx_risk_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('accounts',
    sa.Column('account_number', sa.String(length=24), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('account_type', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tier', sa.String(length=24), nullable=False),
    sa.Column('branch_id', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_account_number'), ['account_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_customer_id'), ['customer_id'], unique=False)

    op.create_table('ip_addresses',
    sa.Column('address', sa.String(length=45), nullable=False),
    sa.Column('asn', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=48), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('isp', sa.String(length=96), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('investigation_count', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ip_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ip_addresses_address'), ['address'], unique=True)

    op.create_table('vulnerabilities',
    sa.Column('vuln_ref', sa.String(length=48), nullable=False),
    sa.Column('disclosure_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('affected_endpoint_id', sa.String(length=36), nullable=True),
    sa.Column('affected_endpoints', sa.JSON(), nullable=False),
    sa.Column('exposure_window_start', sa.DateTime(), nullable=False),
    sa.Column('exposure_window_end', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('disclosed_at', sa.DateTime(), nullable=False),
    sa.Column('remediation_deadline', sa.DateTime(), nullable=True),
    sa.Column('patch_status', sa.String(length=16), nullable=False),
    sa.Column('affected_algorithm', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['affected_endpoint_id'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerabilities_affected_endpoint_id'), ['affected_endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_disclosure_type'), ['disclosure_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_exposure_window_start'), ['exposure_window_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_vuln_ref'), ['vuln_ref'], unique=True)

    op.create_table('auth_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('factor', sa.String(length=24), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('ip_id', sa.String(length=36), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('session_ref', sa.String(length=48), nullable=True),
    sa.Column('endpoint_id', sa.String(length=36), nullable=True),
    sa.Column('browser', sa.String(length=48), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.ForeignKeyConstraint(['ip_id'], ['ip_addresses.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_events', schema=None) as batch_op:
        batch_op.create_index('idx_auth_customer_time', ['customer_id', 'event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_events_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_events_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_events_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_events_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_events_session_ref'), ['session_ref'], unique=False)

    op.create_table('investigations',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('originating_engine', sa.String(length=16), nullable=False),
    sa.Column('lifecycle_stage', sa.String(length=16), nullable=False),
    sa.Column('business_priority', sa.String(length=4), nullable=False),
    sa.Column('assigned_analyst_id', sa.String(length=36), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('primary_customer_id', sa.String(length=36), nullable=True),
    sa.Column('primary_endpoint_id', sa.String(length=36), nullable=True),
    sa.Column('vulnerability_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_analyst_id'], ['analysts.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_business_priority'), ['business_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_investigations_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_originating_engine'), ['originating_engine'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_status'), ['status'], unique=False)

    op.create_table('sessions',
    sa.Column('session_ref', sa.String(length=48), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('ip_id', sa.String(length=36), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('auth_strength', sa.String(length=16), nullable=False),
    sa.Column('behaviour_summary', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['ip_id'], ['ip_addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_session_ref'), ['session_ref'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_start_time'), ['start_time'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('txn_ref', sa.String(length=48), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('source_account_id', sa.String(length=36), nullable=True),
    sa.Column('dest_account_id', sa.String(length=36), nullable=True),
    sa.Column('dest_external', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('session_ref', sa.String(length=48), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('ip_id', sa.String(length=36), nullable=True),
    sa.Column('auth_event_id', sa.BigInteger(), nullable=True),
    sa.Column('endpoint_id', sa.String(length=36), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fraud_status', sa.String(length=16), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['dest_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.ForeignKeyConstraint(['ip_id'], ['ip_addresses.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_txn_customer_time', ['customer_id', 'event_time'], unique=False)
        batch_op.create_index('idx_txn_endpoint_time', ['endpoint_id', 'event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_session_ref'), ['session_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_source_account_id'), ['source_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_txn_ref'), ['txn_ref'], unique=True)

    op.create_table('ai_narratives',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('model_id', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('technical_summary', sa.Text(), nullable=False),
    sa.Column('confidence_explanation', sa.Text(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('recommended_action_summary', sa.Text(), nullable=False),
    sa.Column('structured_refs', sa.JSON(), nullable=False),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('generation_ms', sa.Integer(), nullable=False),
    sa.Column('regeneration_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_narratives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_narratives_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_narratives_is_active'), ['is_active'], unique=False)

    op.create_table('analyst_actions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyst_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyst_actions_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyst_actions_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('business_impact',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('financial_exposure', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('affected_customers', sa.Integer(), nullable=False),
    sa.Column('affected_accounts', sa.Integer(), nullable=False),
    sa.Column('customer_segmentation', sa.JSON(), nullable=False),
    sa.Column('data_sensitivity', sa.String(length=32), nullable=False),
    sa.Column('infrastructure_criticality', sa.String(length=16), nullable=False),
    sa.Column('operational_disruption', sa.String(length=16), nullable=False),
    sa.Column('regulatory_flags', sa.JSON(), nullable=False),
    sa.Column('executive_priority', sa.String(length=4), nullable=False),
    sa.Column('executive_severity', sa.String(length=16), nullable=False),
    sa.Column('estimated_remediation_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('business_confidence', sa.Float(), nullable=False),
    sa.Column('recommended_urgency', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_impact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_impact_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_impact_is_active'), ['is_active'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('evidence_type', sa.String(length=48), nullable=False),
    sa.Column('source_module', sa.String(length=24), nullable=False),
    sa.Column('source_entity_type', sa.String(length=24), nullable=True),
    sa.Column('source_entity_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence_contribution', sa.Float(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('ledger_ref', sa.BigInteger(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('rec_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_rec_type'), ['rec_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_status'), ['status'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=24), nullable=False),
    sa.Column('export_format', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('document_path', sa.String(length=300), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('integrity_hash', sa.String(length=64), nullable=True),
    sa.Column('generation_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_type'), ['report_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_reports_investigation_id'))

    op.drop_table('reports')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_status'))
        batch_op.drop_index(batch_op.f('ix_recommendations_rec_type'))
        batch_op.drop_index(batch_op.f('ix_recommendations_investigation_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_event_time'))
        batch_op.drop_index(batch_op.f('ix_evidence_category'))

    op.drop_table('evidence')
    with op.batch_alter_table('business_impact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_impact_is_active'))
        batch_op.drop_index(batch_op.f('ix_business_impact_investigation_id'))

    op.drop_table('business_impact')
    with op.batch_alter_table('analyst_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyst_actions_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_analyst_actions_event_time'))

    op.drop_table('analyst_actions')
    with op.batch_alter_table('ai_narratives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_narratives_is_active'))
        batch_op.drop_index(batch_op.f('ix_ai_narratives_investigation_id'))

    op.drop_table('ai_narratives')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_txn_ref'))
        batch_op.drop_index(batch_op.f('ix_transactions_source_account_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_session_ref'))
        batch_op.drop_index(batch_op.f('ix_transactions_event_time'))
        batch_op.drop_index(batch_op.f('ix_transactions_endpoint_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_category'))
        batch_op.drop_index('idx_txn_endpoint_time')
        batch_op.drop_index('idx_txn_customer_time')

    op.drop_table('transactions')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_start_time'))
        batch_op.drop_index(batch_op.f('ix_sessions_session_ref'))
        batch_op.drop_index(batch_op.f('ix_sessions_customer_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_status'))
        batch_op.drop_index(batch_op.f('ix_investigations_severity'))
        batch_op.drop_index(batch_op.f('ix_investigations_originating_engine'))
        batch_op.drop_index(batch_op.f('ix_investigations_detected_at'))
        batch_op.drop_index(batch_op.f('ix_investigations_code'))
        batch_op.drop_index(batch_op.f('ix_investigations_category'))
        batch_op.drop_index(batch_op.f('ix_investigations_business_priority'))

    op.drop_table('investigations')
    with op.batch_alter_table('auth_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_events_session_ref'))
        batch_op.drop_index(batch_op.f('ix_auth_events_result'))
        batch_op.drop_index(batch_op.f('ix_auth_events_event_time'))
        batch_op.drop_index(batch_op.f('ix_auth_events_endpoint_id'))
        batch_op.drop_index(batch_op.f('ix_auth_events_customer_id'))
        batch_op.drop_index('idx_auth_customer_time')

    op.drop_table('auth_events')
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_vuln_ref'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_exposure_window_start'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_disclosure_type'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_affected_endpoint_id'))

    op.drop_table('vulnerabilities')
    with op.batch_alter_table('ip_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ip_addresses_address'))

    op.drop_table('ip_addresses')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_customer_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_account_type'))
        batch_op.drop_index(batch_op.f('ix_accounts_account_number'))

    op.drop_table('accounts')
    with op.batch_alter_table('risk_memory', schema=None) as batch_op:
        batch_op.drop_index('idx_risk_entity')

    op.drop_table('risk_memory')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_country'))
        batch_op.drop_index('idx_location_country_city')

    op.drop_table('locations')
    with op.batch_alter_table('ingestion_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_audit_received_at'))
        batch_op.drop_index(batch_op.f('ix_ingestion_audit_correlation_id'))

    op.drop_table('ingestion_audit')
    with op.batch_alter_table('event_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_ledger_session_ref'))
        batch_op.drop_index(batch_op.f('ix_event_ledger_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_event_ledger_event_uid'))
        batch_op.drop_index(batch_op.f('ix_event_ledger_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_ledger_event_time'))
        batch_op.drop_index(batch_op.f('ix_event_ledger_endpoint_id'))
        batch_op.drop_index(batch_op.f('ix_event_ledger_customer_id'))
        batch_op.drop_index('idx_ledger_type_time')
        batch_op.drop_index('idx_ledger_endpoint_time')
        batch_op.drop_index('idx_ledger_customer_time')

    op.drop_table('event_ledger')
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endpoints_endpoint_ref'))
        batch_op.drop_index(batch_op.f('ix_endpoints_criticality'))
        batch_op.drop_index(batch_op.f('ix_endpoints_category'))

    op.drop_table('endpoints')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_fingerprint'))

    op.drop_table('devices')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_customer_type'))
        batch_op.drop_index(batch_op.f('ix_customers_customer_ref'))

    op.drop_table('customers')
    with op.batch_alter_table('analysts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysts_username'))

    op.drop_table('analysts')
    # ### end Alembic commands ###
