"""widen operational_disruption

Revision ID: 2e7df367c298
Revises: fe3cfc894c2c
Create Date: 2026-07-14 23:13:48.082533
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '2e7df367c298'
down_revision: Union[str, None] = 'fe3cfc894c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_impact', 'operational_disruption',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_impact', 'operational_disruption',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
