"""add investigation.meta

Revision ID: fe3cfc894c2c
Revises: 299ec9cc3f9f
Create Date: 2026-07-14 23:03:34.256454
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe3cfc894c2c'
down_revision: Union[str, None] = '299ec9cc3f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('meta', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigations', 'meta')
    # ### end Alembic commands ###
